// Copyright 2026 Cozystack contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: satellite/v1alpha1/satellite.proto

package satellitepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Controller_Hello_FullMethodName              = "/blockstor.satellite.v1alpha1.Controller/Hello"
	Controller_ReportObserved_FullMethodName     = "/blockstor.satellite.v1alpha1.Controller/ReportObserved"
	Controller_ReportPoolCapacity_FullMethodName = "/blockstor.satellite.v1alpha1.Controller/ReportPoolCapacity"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	// Hello is the satellite registration handshake. The satellite sends its
	// identity and capabilities; the controller replies with the cluster
	// identity it should expect.
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// ReportObserved lets the satellite push observed-state updates back to
	// the controller. The controller reads them and updates the matching
	// Resource CRD's status. Client-streaming so satellites can send a
	// continuous flow of events without re-connecting on every change.
	ReportObserved(ctx context.Context, opts ...grpc.CallOption) (Controller_ReportObservedClient, error)
	// ReportPoolCapacity is the periodic capacity-update push: satellite
	// walks each Provider, runs PoolStatus, and ships free/total bytes
	// back so /v1/view/storage-pools surfaces live numbers (linstor-csi
	// GetCapacity, autoplacer free-space ranking).
	ReportPoolCapacity(ctx context.Context, in *ReportPoolCapacityRequest, opts ...grpc.CallOption) (*ReportPoolCapacityResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Controller_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ReportObserved(ctx context.Context, opts ...grpc.CallOption) (Controller_ReportObservedClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[0], Controller_ReportObserved_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerReportObservedClient{stream}
	return x, nil
}

type Controller_ReportObservedClient interface {
	Send(*ResourceObservedEvent) error
	CloseAndRecv() (*ReportObservedResponse, error)
	grpc.ClientStream
}

type controllerReportObservedClient struct {
	grpc.ClientStream
}

func (x *controllerReportObservedClient) Send(m *ResourceObservedEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerReportObservedClient) CloseAndRecv() (*ReportObservedResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReportObservedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) ReportPoolCapacity(ctx context.Context, in *ReportPoolCapacityRequest, opts ...grpc.CallOption) (*ReportPoolCapacityResponse, error) {
	out := new(ReportPoolCapacityResponse)
	err := c.cc.Invoke(ctx, Controller_ReportPoolCapacity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	// Hello is the satellite registration handshake. The satellite sends its
	// identity and capabilities; the controller replies with the cluster
	// identity it should expect.
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	// ReportObserved lets the satellite push observed-state updates back to
	// the controller. The controller reads them and updates the matching
	// Resource CRD's status. Client-streaming so satellites can send a
	// continuous flow of events without re-connecting on every change.
	ReportObserved(Controller_ReportObservedServer) error
	// ReportPoolCapacity is the periodic capacity-update push: satellite
	// walks each Provider, runs PoolStatus, and ships free/total bytes
	// back so /v1/view/storage-pools surfaces live numbers (linstor-csi
	// GetCapacity, autoplacer free-space ranking).
	ReportPoolCapacity(context.Context, *ReportPoolCapacityRequest) (*ReportPoolCapacityResponse, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedControllerServer) ReportObserved(Controller_ReportObservedServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportObserved not implemented")
}
func (UnimplementedControllerServer) ReportPoolCapacity(context.Context, *ReportPoolCapacityRequest) (*ReportPoolCapacityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPoolCapacity not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ReportObserved_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).ReportObserved(&controllerReportObservedServer{stream})
}

type Controller_ReportObservedServer interface {
	SendAndClose(*ReportObservedResponse) error
	Recv() (*ResourceObservedEvent, error)
	grpc.ServerStream
}

type controllerReportObservedServer struct {
	grpc.ServerStream
}

func (x *controllerReportObservedServer) SendAndClose(m *ReportObservedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerReportObservedServer) Recv() (*ResourceObservedEvent, error) {
	m := new(ResourceObservedEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Controller_ReportPoolCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPoolCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ReportPoolCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ReportPoolCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ReportPoolCapacity(ctx, req.(*ReportPoolCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockstor.satellite.v1alpha1.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Controller_Hello_Handler,
		},
		{
			MethodName: "ReportPoolCapacity",
			Handler:    _Controller_ReportPoolCapacity_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportObserved",
			Handler:       _Controller_ReportObserved_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "satellite/v1alpha1/satellite.proto",
}

const (
	Satellite_ApplyResources_FullMethodName    = "/blockstor.satellite.v1alpha1.Satellite/ApplyResources"
	Satellite_ApplyStoragePools_FullMethodName = "/blockstor.satellite.v1alpha1.Satellite/ApplyStoragePools"
	Satellite_DeleteResource_FullMethodName    = "/blockstor.satellite.v1alpha1.Satellite/DeleteResource"
	Satellite_CreateSnapshot_FullMethodName    = "/blockstor.satellite.v1alpha1.Satellite/CreateSnapshot"
	Satellite_DeleteSnapshot_FullMethodName    = "/blockstor.satellite.v1alpha1.Satellite/DeleteSnapshot"
	Satellite_ShipSnapshot_FullMethodName      = "/blockstor.satellite.v1alpha1.Satellite/ShipSnapshot"
)

// SatelliteClient is the client API for Satellite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SatelliteClient interface {
	// ApplyResources is the central reconcile RPC. The controller sends the
	// full set of resources that should live on this node; the satellite
	// brings local state in line with that set (creates new ones, removes
	// ones not in the set, fixes drift).
	ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error)
	// ApplyStoragePools mirrors ApplyResources for storage pools.
	ApplyStoragePools(ctx context.Context, in *ApplyStoragePoolsRequest, opts ...grpc.CallOption) (*ApplyStoragePoolsResponse, error)
	// DeleteResource tears the resource down on this satellite:
	// drbdadm down → DeleteVolume → remove .res file. Idempotent on
	// missing.
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	// CreateSnapshot asks the satellite to take a snapshot of the named
	// resource on this node. Returns once the snapshot is durable on disk.
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// DeleteSnapshot is the dual of CreateSnapshot.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// ShipSnapshot sends a snapshot from this satellite to a peer satellite
	// for clone / replica-expansion flows. Implemented by `zfs send | zfs recv`
	// for ZFS pools and `thin-send-recv` for LVM-thin pools.
	ShipSnapshot(ctx context.Context, in *ShipSnapshotRequest, opts ...grpc.CallOption) (*ShipSnapshotResponse, error)
}

type satelliteClient struct {
	cc grpc.ClientConnInterface
}

func NewSatelliteClient(cc grpc.ClientConnInterface) SatelliteClient {
	return &satelliteClient{cc}
}

func (c *satelliteClient) ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error) {
	out := new(ApplyResourcesResponse)
	err := c.cc.Invoke(ctx, Satellite_ApplyResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelliteClient) ApplyStoragePools(ctx context.Context, in *ApplyStoragePoolsRequest, opts ...grpc.CallOption) (*ApplyStoragePoolsResponse, error) {
	out := new(ApplyStoragePoolsResponse)
	err := c.cc.Invoke(ctx, Satellite_ApplyStoragePools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelliteClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, Satellite_DeleteResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelliteClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, Satellite_CreateSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelliteClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, Satellite_DeleteSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *satelliteClient) ShipSnapshot(ctx context.Context, in *ShipSnapshotRequest, opts ...grpc.CallOption) (*ShipSnapshotResponse, error) {
	out := new(ShipSnapshotResponse)
	err := c.cc.Invoke(ctx, Satellite_ShipSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SatelliteServer is the server API for Satellite service.
// All implementations must embed UnimplementedSatelliteServer
// for forward compatibility
type SatelliteServer interface {
	// ApplyResources is the central reconcile RPC. The controller sends the
	// full set of resources that should live on this node; the satellite
	// brings local state in line with that set (creates new ones, removes
	// ones not in the set, fixes drift).
	ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error)
	// ApplyStoragePools mirrors ApplyResources for storage pools.
	ApplyStoragePools(context.Context, *ApplyStoragePoolsRequest) (*ApplyStoragePoolsResponse, error)
	// DeleteResource tears the resource down on this satellite:
	// drbdadm down → DeleteVolume → remove .res file. Idempotent on
	// missing.
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	// CreateSnapshot asks the satellite to take a snapshot of the named
	// resource on this node. Returns once the snapshot is durable on disk.
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// DeleteSnapshot is the dual of CreateSnapshot.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// ShipSnapshot sends a snapshot from this satellite to a peer satellite
	// for clone / replica-expansion flows. Implemented by `zfs send | zfs recv`
	// for ZFS pools and `thin-send-recv` for LVM-thin pools.
	ShipSnapshot(context.Context, *ShipSnapshotRequest) (*ShipSnapshotResponse, error)
	mustEmbedUnimplementedSatelliteServer()
}

// UnimplementedSatelliteServer must be embedded to have forward compatible implementations.
type UnimplementedSatelliteServer struct {
}

func (UnimplementedSatelliteServer) ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyResources not implemented")
}
func (UnimplementedSatelliteServer) ApplyStoragePools(context.Context, *ApplyStoragePoolsRequest) (*ApplyStoragePoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyStoragePools not implemented")
}
func (UnimplementedSatelliteServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedSatelliteServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedSatelliteServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSatelliteServer) ShipSnapshot(context.Context, *ShipSnapshotRequest) (*ShipSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipSnapshot not implemented")
}
func (UnimplementedSatelliteServer) mustEmbedUnimplementedSatelliteServer() {}

// UnsafeSatelliteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SatelliteServer will
// result in compilation errors.
type UnsafeSatelliteServer interface {
	mustEmbedUnimplementedSatelliteServer()
}

func RegisterSatelliteServer(s grpc.ServiceRegistrar, srv SatelliteServer) {
	s.RegisterService(&Satellite_ServiceDesc, srv)
}

func _Satellite_ApplyResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelliteServer).ApplyResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Satellite_ApplyResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelliteServer).ApplyResources(ctx, req.(*ApplyResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Satellite_ApplyStoragePools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyStoragePoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelliteServer).ApplyStoragePools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Satellite_ApplyStoragePools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelliteServer).ApplyStoragePools(ctx, req.(*ApplyStoragePoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Satellite_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelliteServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Satellite_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelliteServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Satellite_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelliteServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Satellite_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelliteServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Satellite_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelliteServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Satellite_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelliteServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Satellite_ShipSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SatelliteServer).ShipSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Satellite_ShipSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SatelliteServer).ShipSnapshot(ctx, req.(*ShipSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Satellite_ServiceDesc is the grpc.ServiceDesc for Satellite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Satellite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockstor.satellite.v1alpha1.Satellite",
	HandlerType: (*SatelliteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyResources",
			Handler:    _Satellite_ApplyResources_Handler,
		},
		{
			MethodName: "ApplyStoragePools",
			Handler:    _Satellite_ApplyStoragePools_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _Satellite_DeleteResource_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _Satellite_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _Satellite_DeleteSnapshot_Handler,
		},
		{
			MethodName: "ShipSnapshot",
			Handler:    _Satellite_ShipSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "satellite/v1alpha1/satellite.proto",
}
