---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - blockstor.io.blockstor.io
  resources:
  - nodes
  - resourcedefinitions
  - resourcegroups
  - resources
  - storagepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blockstor.io.blockstor.io
  resources:
  - nodes/finalizers
  - resourcedefinitions/finalizers
  - resourcegroups/finalizers
  - resources/finalizers
  - storagepools/finalizers
  verbs:
  - update
- apiGroups:
  - blockstor.io.blockstor.io
  resources:
  - nodes/status
  - resourcedefinitions/status
  - resourcegroups/status
  - resources/status
  - storagepools/status
  verbs:
  - get
  - patch
  - update
