#!/usr/bin/env bash
#
# operator-fuzz.sh — property-based fuzzer for operator CLI workflows.
#
# STATUS: SKELETON ONLY. This commit lays out the interface and the
# verb table. The actual fuzz loop is a follow-up commit (L8 in
# PLAN.md / Test strategy). Do NOT wire this into CI yet.
#
# Concept (the next agent picks this up):
#
#   1. From a fixed seed, generate a sequence of N operator CLI verbs
#      with parameter generators that respect cluster invariants
#      (e.g. don't `r d` a node that has no replica of the RD).
#   2. Replay the sequence against a clean stand using the same
#      machinery as replay-runner.sh.
#   3. After each step, poll Resource Status until it settles
#      (≤ assert_timeout_s). If it never settles, log step + seed +
#      replay-yaml-snippet to $WORK_DIR/finding-<seed>.yaml.
#   4. At teardown, assert the no_orphans invariant. If it fails,
#      same — emit a finding YAML the user can drop into
#      tests/operator-harness/replay/ to make the bug a permanent
#      regression test.
#
# CLI interface (designed; not implemented this commit):
#
#   tests/operator-harness/operator-fuzz.sh \
#       --seed 42 \
#       --steps 50 \
#       --stand dev-kvaps \
#       --output-dir /tmp/fuzz-out \
#       [--shrink]                 # on failure, binary-search for the
#                                    # smallest failing prefix
#
# Verb table (each verb is a generator function in the eventual impl):
#
#   verb           | generator gives                                | precondition
#   ---------------|------------------------------------------------|---------------------------
#   rd c           | unique name from RD pool                       | none
#   vd c           | rd in current set, size 16M..1G                | rd exists, no VD yet
#   r c            | rd, node from worker pool, sp from sp pool     | rd has VD; node has no replica yet
#   r c --diskless | rd, node                                       | rd has ≥1 diskful replica
#   r d            | rd, node where replica exists                  | replica exists; not the last diskful
#   r td --diskless| rd, diskful node                                | ≥2 diskful replicas remain
#   r td --sp X    | rd, diskless node                              | sp valid on that node
#   snap c         | rd, unique snap name                           | rd has ≥1 UpToDate replica
#   snap d         | snap that exists                                | none
#   rg modify --place-count N | rg in current set, N∈[1,3]           | rg exists
#   n d            | node that has no replicas                       | satellite cleanly drained
#   sp c           | node, driver ∈ {LVM, LVM_THIN, ZFS, ZFS_THIN}   | no SP collision on that node
#   sp d           | sp not referenced by any RD                     | none
#
# Generator policy:
#   - reproducible: every roll is `rand $seed $step_index $verb_index`
#   - non-destructive: never generate an `n l` or `sp d` that takes the
#     cluster below minimum quorum on any pre-existing fixture
#   - shrinking: once a failure is found, halve the sequence and re-run
#     to find the smallest reproducer; emit it as a replay YAML
#
# Output format (finding YAML — same schema as tests/operator-harness/replay/*.yaml):
#
#   # finding-<seed>-<step>.yaml
#   name: fuzz-<seed>-<step>
#   description: |
#     Auto-generated by operator-fuzz.sh seed=$SEED step=$STEP
#     Failure: $REASON
#   prerequisites:
#     min_nodes: 3
#   steps:
#     - cmd: [...]
#     ...
#   invariants:
#     - no_orphans
#
# Once landed, the user moves the finding YAML into replay/ → it becomes
# a regression test forever.
#
# ----------------------------------------------------------------------
# TODO for the next agent
# ----------------------------------------------------------------------
#
# [ ] Implement verb generator functions; one per row of the verb table.
# [ ] Implement reproducible rand from (seed, step, verb_index) — use
#     SHA256 over the tuple, mod max.
# [ ] Implement step executor that wraps replay-runner.sh's run_step()
#     to keep one source of truth for "execute step + assert".
# [ ] Implement settle-poll between steps: poll Resource.Status until
#     no replica reports a transient state (Negotiating, Connecting,
#     SyncSource, SyncTarget) — ≤ assert_timeout_s.
# [ ] Implement the no_orphans invariant in the same form as
#     replay-runner.sh (extract into lib if it grows).
# [ ] Implement shrinking: on failure with N steps, retry with N/2,
#     N/4, … until the smallest failing prefix is found.
# [ ] Emit the finding YAML at $WORK_DIR/finding-<seed>-<step>.yaml.
# [ ] Wire as `make fuzz SEED=<n> STEPS=<n>` in the top-level Makefile.
# [ ] Nightly run with a rotating seed; collect findings into a
#     `tests/operator-harness/findings/` queue for triage.
# [ ] Document in PLAN.md → L8 section once landed.

set -euo pipefail

echo "operator-fuzz.sh is a SKELETON in this commit."
echo
echo "The fuzz loop is intentionally not implemented yet — the verb table,"
echo "interface, and finding YAML schema are laid out in the script comments"
echo "so the next agent has a clear contract to fill in."
echo
echo "See the TODO list at the bottom of this file."
exit 0
